name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create Release directory
        run: mkdir -p Release

      - name: Build Windows 64bit
        run: |
          GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-s -w" -o Release/cherrysh-windows-x64.exe .
          cd Release
          zip cherrysh-${{ steps.get_version.outputs.VERSION }}-windows-x64.zip cherrysh-windows-x64.exe
          cd ..

      - name: Build Windows 32bit
        run: |
          GOOS=windows GOARCH=386 CGO_ENABLED=0 go build -ldflags="-s -w" -o Release/cherrysh-windows-x86.exe .
          cd Release
          zip cherrysh-${{ steps.get_version.outputs.VERSION }}-windows-x86.zip cherrysh-windows-x86.exe
          cd ..

      - name: Build Linux 64bit
        run: |
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-s -w" -o Release/cherrysh-linux-x64 .
          cd Release
          tar -czf cherrysh-${{ steps.get_version.outputs.VERSION }}-linux-x64.tar.gz cherrysh-linux-x64
          cd ..

      - name: Build macOS Intel
        run: |
          GOOS=darwin GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-s -w" -o Release/cherrysh-macos-x64 .
          cd Release
          tar -czf cherrysh-${{ steps.get_version.outputs.VERSION }}-macos-x64.tar.gz cherrysh-macos-x64
          cd ..

      - name: Build macOS ARM64
        run: |
          GOOS=darwin GOARCH=arm64 CGO_ENABLED=0 go build -ldflags="-s -w" -o Release/cherrysh-macos-arm64 .
          cd Release
          tar -czf cherrysh-${{ steps.get_version.outputs.VERSION }}-macos-arm64.tar.gz cherrysh-macos-arm64
          cd ..

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Release/cherrysh-${{ steps.get_version.outputs.VERSION }}-windows-x64.zip
            Release/cherrysh-${{ steps.get_version.outputs.VERSION }}-windows-x86.zip
            Release/cherrysh-${{ steps.get_version.outputs.VERSION }}-linux-x64.tar.gz
            Release/cherrysh-${{ steps.get_version.outputs.VERSION }}-macos-x64.tar.gz
            Release/cherrysh-${{ steps.get_version.outputs.VERSION }}-macos-arm64.tar.gz
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 